on: [push, workflow_dispatch]
jobs:
  aws_cdk:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    env: 
      NBA_ENDPOINT: ${{ vars.NBA_ENDPOINT }}
      DEVOPS_PREFIX: ${{ vars.DEVOPS_PREFIX }}
      SPORTS_DATA_API_KEY: ${{ secrets.SPORTS_DATA_API_KEY }}
      RAW_BUCKET: ${{ secrets.RAW_BUCKET }}
      EXTRACTED_BUCKET: ${{ secrets.EXTRACTED_BUCKET }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install moto
          pip install pytest
      - name: Run tests with pytest\
        run: pytest --junitxml=pytest-report.xml
      - name: Pack Lambda
        run: |
          mkdir -p api_lambda, extract_lambda
          cp -r src/api_lambda/main.py api_lambda/
          cp -r src/extract_lambda/main.py extract_lambda/
          # Install dependencies into the package folder
          pip install -r requirements.txt -t api_lambda/
          pip install -r requirements.txt -t extract_lambda/
          # Zip the Lambda function
          cd api_lambda
          zip -r ../api_lambda.zip .
          cd ../extract_lambda
          zip -r ../extract_lambda.zip .
      - name: Configure AWS credentials from repo
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}  
          aws-region: us-east-1
          role-session-name: GitHubActionSession
      - name: Deploy Lambda Function to AWS
        run: |
          API_LAMBDA="devops_day03_api_lambda"
          EXTRACT_LAMBDA="devops_day03_extract_lambda"
          aws lambda update-function-code --function-name $API_LAMBDA --zip-file fileb://api_lambda.zip
          aws lambda update-function-code --function-name $EXTRACT_LAMBDA --zip-file fileb://extract_lambda.zip